/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package netcomp.GUI;

import javax.swing.JPasswordField;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import netcomp.GUI.acciones.AccionCrearClaseMaestro;
import netcomp.NetComp;

/**
 *
 * @author zerg
 */
public class VtnCrearClase extends javax.swing.JFrame {

    public JPasswordField getCrearContraseniaClase() {
        return crearContraseniaClase;
    }

    public JTextArea getCrearDescripcionClase() {
        return crearDescripcionClase;
    }

    public JTextField getCrearNombreClase() {
        return crearNombreClase;
    }

    /**
     * Creates new form crearClase
     */
    public VtnCrearClase() {
        initComponents();
        setTitle("Crear una clase - Parámetros");
        setResizable(false);
    }
    
    //Creación de ventanas del programa
    //Ventana Clase Maestro
    VtnClaseMaestro vtnClaseMaestro = new VtnClaseMaestro();
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        crearClaseTituloVentana = new javax.swing.JLabel();
        crearClaseSeparadorVentana = new javax.swing.JSeparator();
        crearClaseLabelNombre = new javax.swing.JLabel();
        crearNombreClase = new javax.swing.JTextField();
        crearClaseLabelDescripcion = new javax.swing.JLabel();
        crearClaseNombreContrasenia = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        crearDescripcionClase = new javax.swing.JTextArea();
        crearClaseBoton = new javax.swing.JButton();
        crearContraseniaClase = new javax.swing.JPasswordField();
        cancelarCrearClaseBoton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                accionCerrarVentana(evt);
            }
        });

        crearClaseTituloVentana.setFont(new java.awt.Font("Gentium", 1, 18)); // NOI18N
        crearClaseTituloVentana.setText("Crear Clase");

        crearClaseLabelNombre.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        crearClaseLabelNombre.setText("Nombre");

        crearNombreClase.setText("Nombre de su clase");
        crearNombreClase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearNombreClaseActionPerformed(evt);
            }
        });

        crearClaseLabelDescripcion.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        crearClaseLabelDescripcion.setText("Descripción");

        crearClaseNombreContrasenia.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        crearClaseNombreContrasenia.setText("Contraseña");

        crearDescripcionClase.setColumns(20);
        crearDescripcionClase.setRows(5);
        crearDescripcionClase.setText("Una descripción de su clase.");
        jScrollPane1.setViewportView(crearDescripcionClase);

        crearClaseBoton.setAction(new AccionCrearClaseMaestro(this));
        crearClaseBoton.setText("Crear Clase");

        cancelarCrearClaseBoton.setText("Cancelar");
        cancelarCrearClaseBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarCrearClaseBotonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(144, 144, 144)
                .addComponent(crearClaseTituloVentana)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(crearClaseSeparadorVentana)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(crearClaseLabelDescripcion)
                            .addComponent(crearClaseNombreContrasenia)
                            .addComponent(crearClaseLabelNombre))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(crearNombreClase)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 274, Short.MAX_VALUE)
                            .addComponent(crearContraseniaClase)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cancelarCrearClaseBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(crearClaseBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(crearClaseTituloVentana)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(crearClaseSeparadorVentana, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(crearClaseLabelNombre)
                    .addComponent(crearNombreClase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(crearClaseNombreContrasenia)
                    .addComponent(crearContraseniaClase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(crearClaseLabelDescripcion)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cancelarCrearClaseBoton)
                    .addComponent(crearClaseBoton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void crearNombreClaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearNombreClaseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_crearNombreClaseActionPerformed

    private void cancelarCrearClaseBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarCrearClaseBotonActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        NetComp.vtnPrincipal.setVisible(true);
        initComponents();
    }//GEN-LAST:event_cancelarCrearClaseBotonActionPerformed

    private void accionCerrarVentana(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_accionCerrarVentana
        this.dispose();
    }//GEN-LAST:event_accionCerrarVentana

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VtnCrearClase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VtnCrearClase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VtnCrearClase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VtnCrearClase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VtnCrearClase().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelarCrearClaseBoton;
    private javax.swing.JButton crearClaseBoton;
    private javax.swing.JLabel crearClaseLabelDescripcion;
    private javax.swing.JLabel crearClaseLabelNombre;
    private javax.swing.JLabel crearClaseNombreContrasenia;
    private javax.swing.JSeparator crearClaseSeparadorVentana;
    private javax.swing.JLabel crearClaseTituloVentana;
    private javax.swing.JPasswordField crearContraseniaClase;
    private javax.swing.JTextArea crearDescripcionClase;
    private javax.swing.JTextField crearNombreClase;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
